package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"jaeder42.tech/state-trak-local/controllers"
	"jaeder42.tech/state-trak-local/graph/model"
)

// Game is the resolver for the Game field.
func (r *queryResolver) Game(ctx context.Context) (*model.Game, error) {
	var game = controllers.GetGame()

	return &game, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
