type Query {
  game: Game
}

# type Mutation {}

type Game {
  map: String
  frameRate: Int
  players: [Player]
  frames: [FrameState]
}

type Player {
  name: String
  steamId: String
}

type FrameState {
  frame: Int
  time: Float
  playerStates: [PlayerState]
}

type PlayerState {
  name: String
  steamId: String
  kills: Int
  deaths: Int
  assists: Int
  mvps: Int
  team: String
  firing: Boolean
  alive: Boolean
  position: Vector
  eyePosition: Vector
}

type Vector {
  x: Float
  y: Float
}