// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	Map       *string   `json:"map"`
	FrameRate *int      `json:"frameRate"`
	Players   []*Player `json:"players"`
}

type Player struct {
	Name    *string `json:"name"`
	SteamID *string `json:"steamId"`
}
